name: myworkflow

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: AWS ECR
        # You may pin to the exact commit or the version.
        # uses: kciter/aws-ecr-action@79255b7c5aa03dbf6d7c46cff2bfd049874cd98d
        uses: kciter/aws-ecr-action@v4
        with:
          # The AWS access key id
          access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          # The AWS secret access key
          secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          # AWS Account ID
          account_id: ${{secrets.AWS_ACCOUNT_ID}}
          # Name of your ECR repository
          repo: demo
          # The AWS region
          region: us-east-2
          path: .
          name: Dockerfile
          
