name: myworkflow

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: AWS ECR
        uses: kciter/aws-ecr-action@v4
        with:
          access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          account_id: ${{secrets.AWS_ACCOUNT_ID}}
          repo: demo
          region: us-east-2
          
