name: myworkflow

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bdahal17/myreactapp:latest

      - name: AWS ECR
        # You may pin to the exact commit or the version.
        # uses: kciter/aws-ecr-action@79255b7c5aa03dbf6d7c46cff2bfd049874cd98d
        uses: kciter/aws-ecr-action@v4
        with:
          # The AWS access key id
          access_key_id: ${{AWS_ACCESS_KEY_ID}}
          # The AWS secret access key
          secret_access_key: ${{AWS_SECRET_ACCESS_KEY}}
          # AWS Account ID
          account_id: ${{}}
          # Name of your ECR repository
          repo: demo
          # The AWS region
          region: us-east-2
          
